package swedishpack.common.recipes;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.BlockStoneSlab;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import swedishpack.common.library.AddonPackItems;
import swedishpack.common.library.AddonRollingStockItems;
import swedishpack.common.library.SwedishBlockIDs;
import swedishpack.common.library.Swedish_PackAddonInfo;
import train.common.Traincraft;
import train.common.api.crafting.ITierCraftingManager;
import train.common.core.handlers.AbstractRecipeHandler;
import train.common.core.managers.TierRecipeManager;
import train.common.library.BlockIDs;
import train.common.library.ItemIDs;

public class AddonTableRecipeRegister extends AbstractRecipeHandler
{
    public AddonTableRecipeRegister()
    {
        GameRegistry.addRecipe(new ItemStack(SwedishBlockIDs.SvensktVaxelKlotGreySide1.block,1), "Y  ","RG ","BIW", Character.valueOf('Y'), YELLOW_DYE, Character.valueOf('R'), RED_DYE, Character.valueOf('G'), LIGHT_GRAY_DYE, Character.valueOf('B'), Blocks.iron_block, Character.valueOf('I'), Items.iron_ingot, Character.valueOf('W'), Blocks.planks);
        GameRegistry.addShapedRecipe(new ItemStack(SwedishBlockIDs.SvensktVaxelKlotGreySide2.block, 1), "  ", " I", 'I', new ItemStack(SwedishBlockIDs.SvensktVaxelKlotGreySide1.block, 1));
        GameRegistry.addShapedRecipe(new ItemStack(SwedishBlockIDs.SvensktVaxelKlotGreySide1.block, 1), "  ", " I", 'I', new ItemStack(SwedishBlockIDs.SvensktVaxelKlotGreySide2.block, 1));


        GameRegistry.addRecipe(new ItemStack(SwedishBlockIDs.SvensktVaxelKlotGreenSide1.block,1), "Y  ","RG ","BIW", Character.valueOf('Y'), YELLOW_DYE, Character.valueOf('R'), RED_DYE, Character.valueOf('G'), GREEN_DYE, Character.valueOf('B'), Blocks.iron_block, Character.valueOf('I'), Items.iron_ingot, Character.valueOf('W'), Blocks.planks);
        GameRegistry.addShapedRecipe(new ItemStack(SwedishBlockIDs.SvensktVaxelKlotGreenSide2.block, 1), "  ", " I", 'I', new ItemStack(SwedishBlockIDs.SvensktVaxelKlotGreenSide1.block, 1));
        GameRegistry.addShapedRecipe(new ItemStack(SwedishBlockIDs.SvensktVaxelKlotGreenSide1.block, 1), "  ", " I", 'I', new ItemStack(SwedishBlockIDs.SvensktVaxelKlotGreenSide2.block, 1));


        GameRegistry.addRecipe(new ItemStack(SwedishBlockIDs.SvensktVaxelKlotBlackSide1.block,1), "Y  ","RG ","BIW", Character.valueOf('Y'), YELLOW_DYE, Character.valueOf('R'), RED_DYE, Character.valueOf('G'), BLACK_DYE , Character.valueOf('B'), Blocks.iron_block, Character.valueOf('I'), Items.iron_ingot, Character.valueOf('W'), Blocks.planks);
        GameRegistry.addShapedRecipe(new ItemStack(SwedishBlockIDs.SvensktVaxelKlotBlackSide2.block, 1), "  ", " I", 'I', new ItemStack(SwedishBlockIDs.SvensktVaxelKlotBlackSide1.block, 1));
        GameRegistry.addShapedRecipe(new ItemStack(SwedishBlockIDs.SvensktVaxelKlotBlackSide1.block, 1), "  ", " I", 'I', new ItemStack(SwedishBlockIDs.SvensktVaxelKlotBlackSide2.block, 1));

        GameRegistry.addRecipe(new ItemStack(SwedishBlockIDs.PlatformEdgeAsphalt.block,4), "   "," W ","AFS", Character.valueOf('W'), WHITE_DYE, Character.valueOf('A'), new ItemStack(BlockIDs.asphaltSlab.block), Character.valueOf('F'), new ItemStack(BlockIDs.asphaltSlab.block) , Character.valueOf('S'), new ItemStack(Blocks.stone_slab));
        GameRegistry.addShapedRecipe(new ItemStack(SwedishBlockIDs.PlatformEdgeTiles.block, 1), "  ", " I", 'I', new ItemStack(SwedishBlockIDs.PlatformEdgeAsphalt.block, 1));
        GameRegistry.addShapedRecipe(new ItemStack(SwedishBlockIDs.PlatformEdgeThinTiles.block, 1), "  ", " I", 'I', new ItemStack(SwedishBlockIDs.PlatformEdgeTiles.block, 1));
        GameRegistry.addShapedRecipe(new ItemStack(SwedishBlockIDs.PlatformEdgeModern.block, 1), "  ", " I", 'I', new ItemStack(SwedishBlockIDs.PlatformEdgeThinTiles.block, 1));
        GameRegistry.addShapedRecipe(new ItemStack(SwedishBlockIDs.PlatformEdgeAsphalt.block, 1), "  ", " I", 'I', new ItemStack(SwedishBlockIDs.PlatformEdgeModern.block, 1));





        betterAddRecipe(3,new ItemStack(ItemIDs.steel.item, 2), new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.steelcab.item, 2), new ItemStack(ItemIDs.pantograph.item, 2), new ItemStack(ItemIDs.electronicCircuit.item, 1), new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 4), new ItemStack(ItemIDs.fourWheelHeavyweightTruck.item, 2), new ItemStack(ItemIDs.steelframe.item, 2), new ItemStack(ItemIDs.steel.item, 4), new ItemStack(AddonRollingStockItems.minecartSJLittRc1.item), 1);
        betterAddRecipe(3,null, new ItemStack(ItemIDs.steel.item, 1), null, null, null, new ItemStack(ItemIDs.propeller.item, 1), new ItemStack(AddonRollingStockItems.minecartSJLittRc1.item,1), null, new ItemStack(ItemIDs.steel.item, 1), null, new ItemStack(AddonRollingStockItems.minecartSJLittRc2.item), 1);
        betterAddRecipe(3,null, new ItemStack(ItemIDs.steel.item, 1), null, null, new ItemStack(ItemIDs.electmotor.item,1), new ItemStack(ItemIDs.electronicCircuit.item, 1), new ItemStack(AddonRollingStockItems.minecartSJLittRc2.item,1), null, null, null, new ItemStack(AddonRollingStockItems.minecartOBBLitt1043.item), 1);
        betterAddRecipe(3,null, null, null, null, null, new ItemStack(ItemIDs.electronicCircuit.item, 1), new ItemStack(AddonRollingStockItems.minecartOBBLitt1043.item,1), null, null, null, new ItemStack(AddonRollingStockItems.minecartOBBLittRc2.item), 1);
        betterAddRecipe(3,null, new ItemStack(ItemIDs.steel.item, 1), null, null, new ItemStack(ItemIDs.electmotor.item, 1), new ItemStack(ItemIDs.electronicCircuit.item, 1), new ItemStack(AddonRollingStockItems.minecartSJLittRc2.item,1), null, new ItemStack(ItemIDs.steel.item, 1), null, new ItemStack(AddonRollingStockItems.minecartSJLittRc3.item), 1);
        betterAddRecipe(3,null, new ItemStack(ItemIDs.steel.item, 1), null, null, new ItemStack(ItemIDs.electmotor.item, 3), new ItemStack(ItemIDs.electronicCircuit.item, 1), new ItemStack(AddonRollingStockItems.minecartSJLittRc3.item,1), null, new ItemStack(ItemIDs.steel.item, 1), null, new ItemStack(AddonRollingStockItems.minecartSJLittRc4.item), 1);
        betterAddRecipe(3,null, new ItemStack(ItemIDs.steel.item, 1), null, null, null, new ItemStack(ItemIDs.propeller.item, 1), new ItemStack(AddonRollingStockItems.minecartSJLittRc4.item,1), null, new ItemStack(ItemIDs.steel.item, 1), null, new ItemStack(AddonRollingStockItems.minecartSJLittRc5.item), 1);
        betterAddRecipe(3,null, new ItemStack(ItemIDs.steel.item, 1), null, null, new ItemStack(ItemIDs.electmotor.item, 3), new ItemStack(ItemIDs.electronicCircuit.item, 1), new ItemStack(AddonRollingStockItems.minecartSJLittRc5.item,1), null, new ItemStack(ItemIDs.steel.item, 1), null, new ItemStack(AddonRollingStockItems.minecartSJLittRc6.item), 1);
        betterAddRecipe(3,null, null, null, null, new ItemStack(ItemIDs.electmotor.item, 3), BLUE_DYE, new ItemStack(AddonRollingStockItems.minecartSJLittRc6.item,1), null, null, null, new ItemStack(AddonRollingStockItems.minecartSJLittRc7.item), 1);
        betterAddRecipe(3,null, null, null, null, null, new ItemStack(Items.iron_axe), new ItemStack(AddonRollingStockItems.minecartSJLittRc7.item,1), null, null, null, new ItemStack(AddonRollingStockItems.minecartSJLittRc6.item), 1);
        betterAddRecipe(2,new ItemStack(ItemIDs.steel.item, 2), new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.steelcab.item, 2), new ItemStack(ItemIDs.pantograph.item, 2), null , new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 2), new ItemStack(ItemIDs.fourWheelHeavyweightTruck.item, 2), new ItemStack(ItemIDs.steelframe.item, 2), new ItemStack(ItemIDs.steel.item, 4), new ItemStack(AddonRollingStockItems.minecartTGOJLittBt.item), 1);
        betterAddRecipe(2,null, new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.woodenCab.item, 2), new ItemStack(ItemIDs.pantograph.item, 2), null, new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 1), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittD.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot, 2), null, new ItemStack(ItemIDs.ironCab.item, 2), null, new ItemStack(ItemIDs.electronicCircuit.item, 1), new ItemStack(ItemIDs.electmotor.item, 2), new ItemStack(AddonRollingStockItems.minecartSJLittD.item, 1), null, null, new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartSJLittDu2.item), 1);
        betterAddRecipe(2,null, null, null, null, null, new ItemStack(ItemIDs.electmotor.item, 2), new ItemStack(AddonRollingStockItems.minecartSJLittDu2.item, 1), new ItemStack(ItemIDs.ironBogie.item, 1), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittDg2.item), 1);
        betterAddRecipe(2,null, new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.ironCab.item, 2), new ItemStack(ItemIDs.pantograph.item, 2), null, new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 2), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartBJLittDs.item), 1);
        betterAddRecipe(2,null, new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.ironCab.item, 2), new ItemStack(ItemIDs.pantograph.item, 2), null, new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 2), new ItemStack(ItemIDs.fourWheelLightweightTruck.item, 2), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartBJLittBk.item), 1);
        betterAddRecipe(2,null, new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.ironCab.item, 2), new ItemStack(ItemIDs.pantograph.item, 2), null, new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 1), new ItemStack(ItemIDs.fourWheelLightweightTruck.item, 2), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartGBJLittBs.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.ironCab.item, 2), new ItemStack(ItemIDs.pantograph.item, 2), new ItemStack(ItemIDs.propeller.item, 1), new ItemStack(ItemIDs.transformer.item, 2), new ItemStack(ItemIDs.electmotor.item, 4), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittDa.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.controls.item,1), new ItemStack(ItemIDs.ironCab.item, 1), new ItemStack(ItemIDs.pantograph.item, 1), new ItemStack(ItemIDs.propeller.item, 1), new ItemStack(ItemIDs.transformer.item, 2), new ItemStack(ItemIDs.electmotor.item, 6), new ItemStack(ItemIDs.ironBogie.item, 5), new ItemStack(ItemIDs.ironFrame.item, 2), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittDm.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot, 2), null, null, new ItemStack(ItemIDs.copperWireFine.item, 1), new ItemStack(ItemIDs.propeller.item, 1), new ItemStack(ItemIDs.transformer.item, 2), new ItemStack(ItemIDs.electmotor.item, 6), new ItemStack(ItemIDs.ironBogie.item, 5), new ItemStack(ItemIDs.ironFrame.item, 2), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittDm3.item), 1);
        betterAddRecipe(2,null, null, null, new ItemStack(ItemIDs.copperWireFine.item, 1), null, new ItemStack(Items.iron_axe, 1), new ItemStack(AddonRollingStockItems.minecartSJLittDm.item, 1), null, null, null, new ItemStack(AddonRollingStockItems.minecartSJLittDm3.item), 1);
        betterAddRecipe(2,null, new ItemStack(ItemIDs.controls.item,1), new ItemStack(ItemIDs.ironCab.item, 1), new ItemStack(ItemIDs.pantograph.item, 1), null, null, new ItemStack(AddonRollingStockItems.minecartSJLittDm3.item, 1), null, null, null, new ItemStack(AddonRollingStockItems.minecartSJLittDm.item), 1);
        betterAddRecipe(1,null, new ItemStack(ItemIDs.controls.item,1), new ItemStack(ItemIDs.woodenCab.item, 1), new ItemStack(ItemIDs.pantograph.item, 1), null, new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 1), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartSJLittOaA.item), 1);
        betterAddRecipe(1,null, new ItemStack(ItemIDs.controls.item,1), new ItemStack(ItemIDs.woodenCab.item, 1), new ItemStack(ItemIDs.pantograph.item, 1), null, new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 1), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartSJLittObA.item), 1);
        GameRegistry.addShapedRecipe(new ItemStack(AddonRollingStockItems.minecartSJLittOaA.item, 1), "  ", " I", 'I', new ItemStack(AddonRollingStockItems.minecartSJLittObA.item, 1));
        GameRegistry.addShapedRecipe(new ItemStack(AddonRollingStockItems.minecartSJLittObA.item, 1), "  ", " I", 'I', new ItemStack(AddonRollingStockItems.minecartSJLittOaA.item, 1));
        betterAddRecipe(1,null, new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.woodenCab.item, 2), new ItemStack(ItemIDs.pantograph.item, 2), null, new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 1), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 2), new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartSJLittOc.item), 1);
        betterAddRecipe(1,null, new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.woodenCab.item, 2), new ItemStack(ItemIDs.pantograph.item, 2), null, new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 2), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartSJLittOd.item), 1);
        betterAddRecipe(1,null, new ItemStack(ItemIDs.controls.item,1), new ItemStack(ItemIDs.woodenCab.item, 1), new ItemStack(ItemIDs.pantograph.item, 1), null, new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 3), new ItemStack(ItemIDs.ironBogie.item, 5), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittOe.item), 1);
        betterAddRecipe(1,null, new ItemStack(ItemIDs.controls.item,1), new ItemStack(ItemIDs.woodenCab.item, 1), new ItemStack(ItemIDs.pantograph.item, 1), null, new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 3), new ItemStack(ItemIDs.ironBogie.item, 5), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittOf.item), 1);
        betterAddRecipe(1,null, null, null, null, null, null, new ItemStack(AddonRollingStockItems.minecartSJLittOf.item, 1), null, null, new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartSJLittOfs.item), 1);
        betterAddRecipe(1,null, null, null, null, null, new ItemStack(Items.iron_axe, 1), new ItemStack(AddonRollingStockItems.minecartSJLittOfs.item, 1), null, null, null, new ItemStack(AddonRollingStockItems.minecartSJLittOf.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.ironCab.item, 2), new ItemStack(ItemIDs.pantograph.item, 2), null, new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 2), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 2), new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartSJLittFel.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.ironCab.item, 2), null, new ItemStack(ItemIDs.seats.item, 2), null, null, new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 3), new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartSJLittUb.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.ironCab.item, 2), new ItemStack(ItemIDs.pantograph.item, 1), new ItemStack(ItemIDs.seats.item, 2), new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 1), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 3), new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartSJLittX16.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.controls.item,2), new ItemStack(ItemIDs.ironCab.item, 2), null, new ItemStack(ItemIDs.seats.item, 2), new ItemStack(ItemIDs.transmition.item, 1), new ItemStack(ItemIDs.dieselengine.item, 1), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 3), new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartSJLittY6.item), 1);
        betterAddRecipe(2,null, null, null, new ItemStack(ItemIDs.pantograph.item, 1), null, new ItemStack(ItemIDs.transformer.item, 1), new ItemStack(ItemIDs.electmotor.item, 1), null, new ItemStack(AddonRollingStockItems.minecartSJLittUb.item), null, new ItemStack(AddonRollingStockItems.minecartSJLittX16.item), 1);
        betterAddRecipe(2,null, null, null, null, null, new ItemStack(ItemIDs.transmition.item, 1), new ItemStack(ItemIDs.dieselengine.item, 1), null, new ItemStack(AddonRollingStockItems.minecartSJLittUb.item), null, new ItemStack(AddonRollingStockItems.minecartSJLittY6.item), 1);
        betterAddRecipe(2,null, null, new ItemStack(Items.iron_ingot,4), null, null, null, null, null, new ItemStack(AddonRollingStockItems.minecartSJLittUb.item), null, new ItemStack(AddonRollingStockItems.minecartSJLittUDFo20.item), 1);
        betterAddRecipe(2,null, null, new ItemStack(Items.iron_ingot,2), null, null, null, null, null, new ItemStack(AddonRollingStockItems.minecartSJLittUb.item), null, new ItemStack(AddonRollingStockItems.minecartSJLittUBF6Y.item), 1);
        betterAddRecipe(2,null, null, null, null, null, new ItemStack(Items.iron_axe, 1), new ItemStack(AddonRollingStockItems.minecartSJLittUDFo20.item), null, null, null, new ItemStack(AddonRollingStockItems.minecartSJLittUFV.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.ironChimney.item,1), new ItemStack(ItemIDs.ironCab.item, 1), new ItemStack(ItemIDs.controls.item, 1), null, new ItemStack(ItemIDs.transmition.item, 1), new ItemStack(ItemIDs.dieselengine.item, 1), new ItemStack(ItemIDs.ironBogie.item, 3), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartSJLittT31.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.ironChimney.item,1), new ItemStack(ItemIDs.ironCab.item, 1), new ItemStack(ItemIDs.controls.item, 1), null, new ItemStack(ItemIDs.transmition.item, 1), new ItemStack(ItemIDs.dieselengine.item, 1), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittT21.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot, 4), new ItemStack(ItemIDs.ironChimney.item,1), new ItemStack(ItemIDs.ironCab.item, 1), new ItemStack(ItemIDs.controls.item, 1), null, new ItemStack(ItemIDs.transmition.item, 1), new ItemStack(ItemIDs.dieselengine.item, 2), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittT23.item), 1);
        betterAddRecipe(1,null, new ItemStack(ItemIDs.ironChimney.item,1), new ItemStack(ItemIDs.woodenCab.item, 1), null, new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.ironBoiler.item, 2), new ItemStack(ItemIDs.ironFirebox.item, 1), new ItemStack(ItemIDs.ironBogie.item, 3), new ItemStack(ItemIDs.ironFrame.item, 2), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittB1909.item), 1);
        betterAddRecipe(1,null, new ItemStack(ItemIDs.ironChimney.item,1), new ItemStack(ItemIDs.ironCab.item, 1), null, new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.ironBoiler.item, 2), new ItemStack(ItemIDs.ironFirebox.item, 1), new ItemStack(ItemIDs.ironBogie.item, 3), new ItemStack(ItemIDs.ironFrame.item, 2), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittB1919.item), 1);
        betterAddRecipe(1,null, null, new ItemStack(ItemIDs.ironCab.item, 1), null, null, null, new ItemStack(AddonRollingStockItems.minecartSJLittB1909.item, 1), null, null, null, new ItemStack(AddonRollingStockItems.minecartSJLittB1919.item), 1);
        betterAddRecipe(1,new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.ironChimney.item,1), new ItemStack(ItemIDs.ironCab.item, 1), null, null, new ItemStack(ItemIDs.ironBoiler.item, 1), new ItemStack(ItemIDs.ironFirebox.item, 1), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittE.item), 1);
        betterAddRecipe(1,new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.ironChimney.item,1), new ItemStack(ItemIDs.ironCab.item, 1), null, null, new ItemStack(ItemIDs.ironBoiler.item, 1), new ItemStack(ItemIDs.ironFirebox.item, 1), new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 2), new ItemStack(Items.iron_ingot, 4), new ItemStack(AddonRollingStockItems.minecartSJLittE2.item), 1);
        betterAddRecipe(1,null, null, null, null, null, null, new ItemStack(AddonRollingStockItems.minecartSJLittE.item, 1), null, new ItemStack(ItemIDs.ironFrame.item, 1), null, new ItemStack(AddonRollingStockItems.minecartSJLittE2.item), 1);
        betterAddRecipe(2,null, new ItemStack(ItemIDs.ironChimney.item,1), new ItemStack(ItemIDs.ironCab.item, 1), null, new ItemStack(Items.iron_ingot, 2), new ItemStack(ItemIDs.ironBoiler.item, 2), new ItemStack(ItemIDs.firebox.item, 1), new ItemStack(ItemIDs.ironBogie.item, 5), new ItemStack(ItemIDs.ironFrame.item, 3), new ItemStack(Items.iron_ingot, 2), new ItemStack(AddonRollingStockItems.minecartSJLittF.item), 1);
        betterAddRecipe(1,null, null, null, null, new ItemStack(Items.coal, 1), null, null, new ItemStack(ItemIDs.ironBogie.item, 3), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot,2), new ItemStack(AddonRollingStockItems.minecartSJLittCTender.item), 1);
        betterAddRecipe(1,null, null, null, null, new ItemStack(Items.coal, 2), null, null, new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot,2), new ItemStack(AddonRollingStockItems.minecartSJLittATender.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot, 2), null, null, null, new ItemStack(Items.coal, 3), null, null, new ItemStack(ItemIDs.ironBogie.item, 4), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot,2), new ItemStack(AddonRollingStockItems.minecartSJLittFTender.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot,4), null, null, null, new ItemStack(Blocks.planks, 1), null, null, new ItemStack(ItemIDs.ironBogie.item, 2), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot,4), new ItemStack(AddonRollingStockItems.minecartSJLittO.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot,2), null, null, null, new ItemStack(Blocks.planks, 1), null, null, new ItemStack(ItemIDs.ironBogie.item, 2), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot,2), new ItemStack(AddonRollingStockItems.minecartSJLittOs.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot,3), null, null, null, new ItemStack(Blocks.planks, 1), null, null, new ItemStack(ItemIDs.ironBogie.item, 3), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot,3), new ItemStack(AddonRollingStockItems.minecartSJLittOa.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot,5), null, null, null, new ItemStack(Blocks.planks, 1), null, null, new ItemStack(ItemIDs.ironBogie.item, 2), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot,5), new ItemStack(AddonRollingStockItems.minecartSJLittOs_w.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot,1), null, new ItemStack(ItemIDs.woodenCab.item,2), null, new ItemStack(Blocks.planks, 1), null, null, new ItemStack(ItemIDs.ironBogie.item, 2), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot,2), new ItemStack(AddonRollingStockItems.minecartSJLittG.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot,1), null, null, null, null, new ItemStack(Items.bucket, 1), null, new ItemStack(ItemIDs.ironBogie.item, 2), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot,2), new ItemStack(AddonRollingStockItems.minecartSJLittQ12.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot,6), null, null, null, new ItemStack(Blocks.gravel, 1), null, null, new ItemStack(ItemIDs.ironBogie.item, 2), new ItemStack(ItemIDs.ironFrame.item, 2), new ItemStack(Items.iron_ingot,2), new ItemStack(AddonRollingStockItems.minecartSJLittElos.item), 1);
        betterAddRecipe(2,new ItemStack(Items.iron_ingot,2), null, null, null, new ItemStack(Blocks.planks, 1), new ItemStack(Blocks.chest, 1), null, new ItemStack(ItemIDs.ironBogie.item, 2), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot,5), new ItemStack(AddonRollingStockItems.minecartSJLittLgs.item), 1);
        betterAddRecipe(3,null, null, null, null, null, new ItemStack(Blocks.chest, 1), null, new ItemStack(ItemIDs.bogie.item, 2), new ItemStack(ItemIDs.steelframe.item, 1), new ItemStack(ItemIDs.steel.item,2), new ItemStack(AddonRollingStockItems.minecartSJLittLgns_081.item), 1);
        betterAddRecipe(1,null, null, null, null, new ItemStack(Blocks.iron_ore, 1), null, null, new ItemStack(ItemIDs.ironBogie.item, 3), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot,2), new ItemStack(AddonRollingStockItems.minecartSJLittM1.item), 1);
        betterAddRecipe(1,null, null, null, null, new ItemStack(Blocks.gravel, 1), null, null, new ItemStack(ItemIDs.ironBogie.item, 3), new ItemStack(ItemIDs.ironFrame.item, 1), new ItemStack(Items.iron_ingot,2), new ItemStack(AddonRollingStockItems.minecartSJLittM1.item), 1);




    }

    public static void betterAddRecipe(int tier, ItemStack top1, ItemStack top2,
                                       ItemStack top3, ItemStack top4, ItemStack mid1, ItemStack mid2, ItemStack mid3,
                                       ItemStack bottom1, ItemStack bottom2, ItemStack bottom3, ItemStack output, int outputSize) {
        ITierCraftingManager cm = TierRecipeManager.getInstance();
        cm.addRecipe(tier, top1, bottom1, bottom2, bottom3, top2, top3, mid2, mid3, mid1, top4, output, outputSize);
    }



}
